spring:
  config:
    activate:
      on-profile: default
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  data.mongodb:
    username: rootuser
    password: rootpass
    database: chat_db
    port: 27017
    host: localhost
    authentication-database: admin
jwt.secret : hahaha
server.error.include-message: always