spring:
  config:
    activate:
      on-profile: dev
  data.mongodb:
    username: rootuser
    password: rootpass
    database: chat_db
    port: 27017
    host: localhost
    authentication-database: admin
jwt.secret : hahaha
server.error.include-message: always