spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testowa
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql : true
    hibernate:
      ddl-auto : create-drop
  data.mongodb:
    username: rootuser
    password: rootpass
    database: chat_db
    port: 27017
    host: localhost
    authentication-database: admin
jwt.secret : hahaha
server.error.include-message: always